name: README fetcher

on:
  push:
    branches: [main]
  schedule:
    # Every 5 minutes
    - cron: "*/5 * * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Fetch READMEs
        run: |
          for unit in `curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/users/Tarang74/repos?per_page=200 | jq '.[] | select(.topics | contains(["qut"])) | .name'`; do
              # Remove extra quotes
              unit=$(echo $unit | tr -d '"')
              # Download README
              curl "https://raw.githubusercontent.com/Tarang74/$unit/main/README.md" --output $unit.md
          done
      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
      - name: Commit and push changes
        run: |
          if [[ -z "$(git status --porcelain $STATUS_ARGS $PATHSPEC)" ]]; then
            echo "No changes to commit"
          else
            git add .
            git commit -m "Update READMEs"
            git push
          fi
