name: README Updater

on:
  schedule:
    # Every 5 minutes
    - cron: "*/5 * * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch READMEs
        run: |
          for unit in `curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/users/Tarang74/repos?per_page=200 | jq '.[] | select(.topics | contains(["qut"])) | .name'`; do
              # Remove extra quotes
              unit=$(echo $unit | tr -d '"')
              # Download README
              curl "https://raw.githubusercontent.com/Tarang74/$unit/main/README.md" --output $unit.md
          done
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "READMEs Updated"
          git push
